let app = new Vue({
    el: '#app',
    data: function () {
        return {
            activeName: 'first',
            navItems: [
                { id:0,value: "推荐音乐", link: "#" },
                { id:1,value: "热歌榜", link: "#" },
                { id:2,value: "搜索", link: "#" }
            ],
            results: [
                {
                    "id": 1313052960,
                    "type": 4,
                    "name": "从无到有",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": false,
                    "song": {
                        "name": "从无到有",
                        "id": 1313052960,
                        "position": 1,
                        "alias": ["电视剧《创业时代》片尾主题曲"],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 1412830,
                        "disc": "1",
                        "no": 1,
                        "artists": [
                            {
                                "name": "毛不易",
                                "id": 12138269,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "从无到有",
                            "id": 73471094,
                            "type": "EP/Single",
                            "size": 1,
                            "picId": 109951163592648368,
                            "blurPicUrl": "http://p1.music.126.net/O6Ur0E4Qs0FIDfp-lKHYZA==/109951163592648368.jpg",
                            "companyId": 0,
                            "pic": 109951163592648368,
                            "picUrl": "http://p1.music.126.net/O6Ur0E4Qs0FIDfp-lKHYZA==/109951163592648368.jpg",
                            "publishTime": 1538928000007,
                            "description": "",
                            "tags": "",
                            "company": "华策音乐",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": ["电视剧《创业时代》片尾主题曲"],
                            "status": 1,
                            "copyrightId": 1412830,
                            "commentThreadId": "R_AL_3_73471094",
                            "artists": [
                                {
                                    "name": "毛不易",
                                    "id": 12138269,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163592648368"
                        },
                        "starred": false,
                        "popularity": 0.0,
                        "score": 0,
                        "starredNum": 0,
                        "duration": 277498,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1313052960",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 0,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 0,
                        "bMusic": {
                            "name": null,
                            "id": 3456971886,
                            "size": 4440860,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 277498,
                            "volumeDelta": -0.67
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": null,
                            "id": 3456971884,
                            "size": 11102085,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 277498,
                            "volumeDelta": -1.09
                        },
                        "mMusic": {
                            "name": null,
                            "id": 3456971885,
                            "size": 6661268,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 277498,
                            "volumeDelta": -0.83
                        },
                        "lMusic": {
                            "name": null,
                            "id": 3456971886,
                            "size": 4440860,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 277498,
                            "volumeDelta": -0.67
                        },
                        "privilege": {
                            "id": 1313052960,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 999000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 0,
                            "preSell": false
                        }
                    },
                    "alg": "featured"
                },
                {
                    "id": 1313052974,
                    "type": 4,
                    "name": "新三部曲 (Live)",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": false,
                    "song": {
                        "name": "新三部曲 (Live)",
                        "id": 1313052974,
                        "position": 8,
                        "alias": [],
                        "status": 0,
                        "fee": 0,
                        "copyrightId": 1376818,
                        "disc": "",
                        "no": 8,
                        "artists": [
                            {
                                "name": "艾热",
                                "id": 1203045,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "中国新说唱 第13期",
                            "id": 73681733,
                            "type": "专辑",
                            "size": 0,
                            "picId": 109951163589728383,
                            "blurPicUrl": "http://p1.music.126.net/WlkSXIjLZcenMU1g0anGeg==/109951163589728383.jpg",
                            "companyId": 0,
                            "pic": 109951163589728383,
                            "picUrl": "http://p1.music.126.net/WlkSXIjLZcenMU1g0anGeg==/109951163589728383.jpg",
                            "publishTime": 1538755200007,
                            "description": "",
                            "tags": "",
                            "company": "爱奇艺",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 0,
                            "copyrightId": 1376818,
                            "commentThreadId": "R_AL_3_73681733",
                            "artists": [
                                {
                                    "name": "群星",
                                    "id": 122455,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "现场版",
                            "transName": null,
                            "picId_str": "109951163589728383"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 282035,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1313052974",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 0,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 0,
                        "bMusic": {
                            "name": "",
                            "id": 3457735233,
                            "size": 4513585,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 282035,
                            "volumeDelta": -3.0
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": "",
                            "id": 3457735231,
                            "size": 11283897,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 282035,
                            "volumeDelta": -3.0
                        },
                        "mMusic": {
                            "name": "",
                            "id": 3457735232,
                            "size": 6770355,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 282035,
                            "volumeDelta": -3.0
                        },
                        "lMusic": {
                            "name": "",
                            "id": 3457735233,
                            "size": 4513585,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 282035,
                            "volumeDelta": -3.0
                        },
                        "privilege": {
                            "id": 1313052974,
                            "fee": 0,
                            "payed": 0,
                            "st": 0,
                            "pl": 320000,
                            "dl": 320000,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 999000,
                            "fl": 320000,
                            "toast": false,
                            "flag": 128,
                            "preSell": false
                        }
                    },
                    "alg": "featured"
                },
                {
                    "id": 1314780499,
                    "type": 4,
                    "name": "1999",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": false,
                    "song": {
                        "name": "1999",
                        "id": 1314780499,
                        "position": 0,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 7002,
                        "disc": "1",
                        "no": 1,
                        "artists": [
                            {
                                "name": "Charli XCX",
                                "id": 53092,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            {
                                "name": "Troye Sivan",
                                "id": 45129,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "1999",
                            "id": 73749871,
                            "type": "EP/Single",
                            "size": 1,
                            "picId": 109951163586538233,
                            "blurPicUrl": "http://p1.music.126.net/b7WyInzyJxF5oHkAok1FbA==/109951163586538233.jpg",
                            "companyId": 0,
                            "pic": 109951163586538233,
                            "picUrl": "http://p1.music.126.net/b7WyInzyJxF5oHkAok1FbA==/109951163586538233.jpg",
                            "publishTime": 1538668800007,
                            "description": "",
                            "tags": "",
                            "company": "华纳音乐",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 3,
                            "copyrightId": 7002,
                            "commentThreadId": "R_AL_3_73749871",
                            "artists": [
                                {
                                    "name": "Charli XCX",
                                    "id": 53092,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                },
                                {
                                    "name": "Troye Sivan",
                                    "id": 45129,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163586538233"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 189048,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1314780499",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 1,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 0,
                        "bMusic": {
                            "name": null,
                            "id": 3456429353,
                            "size": 3025232,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 189048,
                            "volumeDelta": -1.64
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": null,
                            "id": 3456429351,
                            "size": 7563015,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 189048,
                            "volumeDelta": -1.97
                        },
                        "mMusic": {
                            "name": null,
                            "id": 3456429352,
                            "size": 4537826,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 189048,
                            "volumeDelta": -1.74
                        },
                        "lMusic": {
                            "name": null,
                            "id": 3456429353,
                            "size": 3025232,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 189048,
                            "volumeDelta": -1.64
                        },
                        "privilege": {
                            "id": 1314780499,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 320000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 4,
                            "preSell": false
                        }
                    },
                    "alg": "featured"
                },
                {
                    "id": 1313096578,
                    "type": 4,
                    "name": "Shallow",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "Shallow",
                        "id": 1313096578,
                        "position": 1,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 7003,
                        "disc": "1",
                        "no": 12,
                        "artists": [
                            {
                                "name": "Lady Gaga",
                                "id": 64147,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            {
                                "name": "Bradley Cooper",
                                "id": 14802030,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "A Star Is Born Soundtrack",
                            "id": 73781284,
                            "type": "专辑",
                            "size": 34,
                            "picId": 109951163586816352,
                            "blurPicUrl": "http://p2.music.126.net/8VK2ZVfu_AdspaXhY720pg==/109951163586816352.jpg",
                            "companyId": 0,
                            "pic": 109951163586816352,
                            "picUrl": "http://p2.music.126.net/8VK2ZVfu_AdspaXhY720pg==/109951163586816352.jpg",
                            "publishTime": 1538668800007,
                            "description": "",
                            "tags": "",
                            "company": "环球唱片",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": ["电影《一个明星的诞生》原声带"],
                            "status": 3,
                            "copyrightId": 7003,
                            "commentThreadId": "R_AL_3_73781284",
                            "artists": [
                                {
                                    "name": "Lady Gaga",
                                    "id": 64147,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                },
                                {
                                    "name": "Bradley Cooper",
                                    "id": 14802030,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163586816352"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 215771,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1313096578",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 1,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 10798473,
                        "bMusic": {
                            "name": "",
                            "id": 3451252517,
                            "size": 3452804,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 215771,
                            "volumeDelta": -2.0
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": "",
                            "id": 3451252515,
                            "size": 8631946,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 215771,
                            "volumeDelta": -2.0
                        },
                        "mMusic": {
                            "name": "",
                            "id": 3451252516,
                            "size": 5179185,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 215771,
                            "volumeDelta": -2.0
                        },
                        "lMusic": {
                            "name": "",
                            "id": 3451252517,
                            "size": 3452804,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 215771,
                            "volumeDelta": -2.0
                        },
                        "exclusive": false,
                        "privilege": {
                            "id": 1313096578,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 320000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 4,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1313052240,
                    "type": 4,
                    "name": "孔雀",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "孔雀",
                        "id": 1313052240,
                        "position": 1,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 1411826,
                        "disc": "",
                        "no": 1,
                        "artists": [
                            {
                                "name": "吉克隽逸",
                                "id": 166018,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "Garden花园",
                            "id": 73471928,
                            "type": "专辑",
                            "size": 3,
                            "picId": 109951163574982030,
                            "blurPicUrl": "http://p2.music.126.net/wz-Uxft4a-ICQZj3wuxbMA==/109951163574982030.jpg",
                            "companyId": 0,
                            "pic": 109951163574982030,
                            "picUrl": "http://p2.music.126.net/wz-Uxft4a-ICQZj3wuxbMA==/109951163574982030.jpg",
                            "publishTime": 1538150400007,
                            "description": "",
                            "tags": "",
                            "company": "天浩盛世",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 0,
                            "copyrightId": 1411826,
                            "commentThreadId": "R_AL_3_73471928",
                            "artists": [
                                {
                                    "name": "吉克隽逸",
                                    "id": 166018,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163574982030"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 274600,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1313052240",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 2,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 0,
                        "bMusic": {
                            "name": null,
                            "id": 3452305432,
                            "size": 4394884,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 274600,
                            "volumeDelta": -2.83
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": null,
                            "id": 3452305430,
                            "size": 10987146,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 274600,
                            "volumeDelta": -3.25
                        },
                        "mMusic": {
                            "name": null,
                            "id": 3452305431,
                            "size": 6592305,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 274600,
                            "volumeDelta": -3.0
                        },
                        "lMusic": {
                            "name": null,
                            "id": 3452305432,
                            "size": 4394884,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 274600,
                            "volumeDelta": -2.83
                        },
                        "exclusive": true,
                        "privilege": {
                            "id": 1313052240,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 999000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 256,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1311782175,
                    "type": 4,
                    "name": "Diamond Heart",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "Diamond Heart",
                        "id": 1311782175,
                        "position": 0,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 7001,
                        "disc": "1",
                        "no": 1,
                        "artists": [
                            {
                                "name": "Alan Walker",
                                "id": 1045123,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            {
                                "name": "Sophia Somajo",
                                "id": 77713,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "Diamond Heart",
                            "id": 73526604,
                            "type": "EP/Single",
                            "size": 1,
                            "picId": 109951163561939242,
                            "blurPicUrl": "http://p2.music.126.net/_FXzeT6oFgayo1ztTZOr-g==/109951163561939242.jpg",
                            "companyId": 0,
                            "pic": 109951163561939242,
                            "picUrl": "http://p2.music.126.net/_FXzeT6oFgayo1ztTZOr-g==/109951163561939242.jpg",
                            "publishTime": 1538064000007,
                            "description": "",
                            "tags": "",
                            "company": "索尼音乐",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 3,
                            "copyrightId": 7001,
                            "commentThreadId": "R_AL_3_73526604",
                            "artists": [
                                {
                                    "name": "Alan Walker",
                                    "id": 1045123,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                },
                                {
                                    "name": "Sophia Somajo",
                                    "id": 77713,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163561939242"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 239882,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1311782175",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 1,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 10798525,
                        "bMusic": {
                            "name": null,
                            "id": 3451048515,
                            "size": 3838581,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 239882,
                            "volumeDelta": -1.27
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": null,
                            "id": 3451048513,
                            "size": 9596387,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 239882,
                            "volumeDelta": -1.62
                        },
                        "mMusic": {
                            "name": null,
                            "id": 3451048514,
                            "size": 5757849,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 239882,
                            "volumeDelta": -1.4
                        },
                        "lMusic": {
                            "name": null,
                            "id": 3451048515,
                            "size": 3838581,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 239882,
                            "volumeDelta": -1.27
                        },
                        "exclusive": false,
                        "privilege": {
                            "id": 1311782175,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 320000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 260,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1310906383,
                    "type": 4,
                    "name": "Head Above Water",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "Head Above Water",
                        "id": 1310906383,
                        "position": 1,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 685011,
                        "disc": "1",
                        "no": 1,
                        "artists": [
                            {
                                "name": "Avril Lavigne",
                                "id": 46490,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "Head Above Water",
                            "id": 73257377,
                            "type": "EP/Single",
                            "size": 1,
                            "picId": 109951163561900810,
                            "blurPicUrl": "http://p2.music.126.net/S1pHCS9mf8JEmzyiia0cag==/109951163561900810.jpg",
                            "companyId": 0,
                            "pic": 109951163561900810,
                            "picUrl": "http://p2.music.126.net/S1pHCS9mf8JEmzyiia0cag==/109951163561900810.jpg",
                            "publishTime": 1537315200000,
                            "description": "",
                            "tags": "",
                            "company": "BMG Rights Management (US) LLC",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 1,
                            "copyrightId": 685011,
                            "commentThreadId": "R_AL_3_73257377",
                            "artists": [
                                {
                                    "name": "Avril Lavigne",
                                    "id": 46490,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163561900810"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 220850,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1310906383",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 2,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 10799411,
                        "bMusic": {
                            "name": null,
                            "id": 3448207727,
                            "size": 3534724,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 220850,
                            "volumeDelta": -1.79
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": null,
                            "id": 3448207725,
                            "size": 8836746,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 220850,
                            "volumeDelta": -2.16
                        },
                        "mMusic": {
                            "name": null,
                            "id": 3448207726,
                            "size": 5302065,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 220850,
                            "volumeDelta": -1.91
                        },
                        "lMusic": {
                            "name": null,
                            "id": 3448207727,
                            "size": 3534724,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 220850,
                            "volumeDelta": -1.79
                        },
                        "exclusive": false,
                        "privilege": {
                            "id": 1310906383,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 999000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 0,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1311346598,
                    "type": 4,
                    "name": "考虑到可能再也见不到你",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "考虑到可能再也见不到你",
                        "id": 1311346598,
                        "position": 5,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 729013,
                        "disc": "1",
                        "no": 7,
                        "artists": [
                            {
                                "name": "徐良",
                                "id": 5929,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "考虑到可能再也见不到你",
                            "id": 73470775,
                            "type": "专辑",
                            "size": 10,
                            "picId": 109951163569789624,
                            "blurPicUrl": "http://p2.music.126.net/CKumVHRBsIFExQoK1Y77aQ==/109951163569789624.jpg",
                            "companyId": 0,
                            "pic": 109951163569789624,
                            "picUrl": "http://p2.music.126.net/CKumVHRBsIFExQoK1Y77aQ==/109951163569789624.jpg",
                            "publishTime": 1537891200007,
                            "description": "",
                            "tags": "",
                            "company": "大象无形",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 0,
                            "copyrightId": 729013,
                            "commentThreadId": "R_AL_3_73470775",
                            "artists": [
                                {
                                    "name": "徐良",
                                    "id": 5929,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163569789624"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 249514,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1311346598",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 0,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 10798365,
                        "bMusic": {
                            "name": "",
                            "id": 3450013066,
                            "size": 3993226,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 249514,
                            "volumeDelta": 0.0
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": "",
                            "id": 3450013064,
                            "size": 9982999,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 249514,
                            "volumeDelta": -1.0
                        },
                        "mMusic": {
                            "name": "",
                            "id": 3450013065,
                            "size": 5989817,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 249514,
                            "volumeDelta": -1.0
                        },
                        "lMusic": {
                            "name": "",
                            "id": 3450013066,
                            "size": 3993226,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 249514,
                            "volumeDelta": 0.0
                        },
                        "exclusive": true,
                        "privilege": {
                            "id": 1311346598,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 999000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 0,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1307958308,
                    "type": 4,
                    "name": "I Don't Know",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "I Don't Know",
                        "id": 1307958308,
                        "position": 0,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 7003,
                        "disc": "1",
                        "no": 2,
                        "artists": [
                            {
                                "name": "Paul McCartney",
                                "id": 41135,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "Egypt Station",
                            "id": 73106039,
                            "type": "专辑",
                            "size": 16,
                            "picId": 109951163537362151,
                            "blurPicUrl": "http://p2.music.126.net/pglVncSAg1d9Ml02iumayQ==/109951163537362151.jpg",
                            "companyId": 0,
                            "pic": 109951163537362151,
                            "picUrl": "http://p2.music.126.net/pglVncSAg1d9Ml02iumayQ==/109951163537362151.jpg",
                            "publishTime": 1536249600007,
                            "description": "",
                            "tags": "",
                            "company": "环球唱片",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 3,
                            "copyrightId": 7003,
                            "commentThreadId": "R_AL_3_73106039",
                            "artists": [
                                {
                                    "name": "Paul McCartney",
                                    "id": 41135,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163537362151"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 266971,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1307958308",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 1,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 0,
                        "bMusic": {
                            "name": "",
                            "id": 3437599388,
                            "size": 4272004,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 266971,
                            "volumeDelta": 0.0
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": "",
                            "id": 3437599386,
                            "size": 10679946,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 266971,
                            "volumeDelta": 0.0
                        },
                        "mMusic": {
                            "name": "",
                            "id": 3437599387,
                            "size": 6407985,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 266971,
                            "volumeDelta": 0.0
                        },
                        "lMusic": {
                            "name": "",
                            "id": 3437599388,
                            "size": 4272004,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 266971,
                            "volumeDelta": 0.0
                        },
                        "exclusive": false,
                        "privilege": {
                            "id": 1307958308,
                            "fee": 8,
                            "payed": 0,
                            "st": 0,
                            "pl": 128000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 320000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 4,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                },
                {
                    "id": 1300423074,
                    "type": 4,
                    "name": "可一可再",
                    "copywriter": null,
                    "picUrl": null,
                    "canDislike": true,
                    "song": {
                        "name": "可一可再",
                        "id": 1300423074,
                        "position": 1,
                        "alias": [],
                        "status": 0,
                        "fee": 8,
                        "copyrightId": 7003,
                        "disc": "",
                        "no": 0,
                        "artists": [
                            {
                                "name": "陈奕迅",
                                "id": 2116,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            {
                                "name": "eason and the duo band",
                                "id": 14713083,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            }
                        ],
                        "album": {
                            "name": "可一可再",
                            "id": 72072277,
                            "type": "EP/Single",
                            "size": 1,
                            "picId": 109951163512803446,
                            "blurPicUrl": "http://p2.music.126.net/ihkYgnwvjcDiQf8kmnESig==/109951163512803446.jpg",
                            "companyId": 0,
                            "pic": 109951163512803446,
                            "picUrl": "http://p2.music.126.net/ihkYgnwvjcDiQf8kmnESig==/109951163512803446.jpg",
                            "publishTime": 1535040000007,
                            "description": "",
                            "tags": "",
                            "company": "环球唱片",
                            "briefDesc": "",
                            "artist": {
                                "name": "",
                                "id": 0,
                                "picId": 0,
                                "img1v1Id": 0,
                                "briefDesc": "",
                                "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                "albumSize": 0,
                                "alias": [],
                                "trans": "",
                                "musicSize": 0
                            },
                            "songs": [],
                            "alias": [],
                            "status": 3,
                            "copyrightId": 7003,
                            "commentThreadId": "R_AL_3_72072277",
                            "artists": [
                                {
                                    "name": "陈奕迅",
                                    "id": 2116,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                },
                                {
                                    "name": "eason and the duo band",
                                    "id": 14713083,
                                    "picId": 0,
                                    "img1v1Id": 0,
                                    "briefDesc": "",
                                    "picUrl": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "img1v1Url": "http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                                    "albumSize": 0,
                                    "alias": [],
                                    "trans": "",
                                    "musicSize": 0
                                }
                            ],
                            "subType": "录音室版",
                            "transName": null,
                            "picId_str": "109951163512803446"
                        },
                        "starred": false,
                        "popularity": 100.0,
                        "score": 100,
                        "starredNum": 0,
                        "duration": 284656,
                        "playedNum": 0,
                        "dayPlays": 0,
                        "hearTime": 0,
                        "ringtone": null,
                        "crbt": null,
                        "audition": null,
                        "copyFrom": "",
                        "commentThreadId": "R_SO_4_1300423074",
                        "rtUrl": null,
                        "ftype": 0,
                        "rtUrls": [],
                        "copyright": 0,
                        "transName": null,
                        "sign": null,
                        "rurl": null,
                        "mvid": 5966724,
                        "bMusic": {
                            "name": "",
                            "id": 3431031147,
                            "size": 4554963,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 284656,
                            "volumeDelta": -1.0
                        },
                        "mp3Url": null,
                        "rtype": 0,
                        "hMusic": {
                            "name": "",
                            "id": 3431031145,
                            "size": 11387342,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 320000,
                            "playTime": 284656,
                            "volumeDelta": -1.0
                        },
                        "mMusic": {
                            "name": "",
                            "id": 3431031146,
                            "size": 6832422,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 192000,
                            "playTime": 284656,
                            "volumeDelta": -1.0
                        },
                        "lMusic": {
                            "name": "",
                            "id": 3431031147,
                            "size": 4554963,
                            "extension": "mp3",
                            "sr": 44100,
                            "dfsId": 0,
                            "bitrate": 128000,
                            "playTime": 284656,
                            "volumeDelta": -1.0
                        },
                        "exclusive": false,
                        "privilege": {
                            "id": 1300423074,
                            "fee": 0,
                            "payed": 0,
                            "st": 0,
                            "pl": 320000,
                            "dl": 0,
                            "sp": 7,
                            "cp": 1,
                            "subp": 1,
                            "cs": false,
                            "maxbr": 320000,
                            "fl": 128000,
                            "toast": false,
                            "flag": 4,
                            "preSell": false
                        }
                    },
                    "alg": "hot_server"
                }
            ],
            recommendLists:[
                {id:0,value:'华语速爆新歌',imgSrc:'http://p1.music.126.net/odWKigBn5F5hkm19XOvpxg==/109951163594051457.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'2.7亿'},
                {id:1,value:'急需一曲小调来拯救你的假期综合征',imgSrc:'http://p1.music.126.net/buIurXYn7-fjhLZu6UUdEg==/109951163580087511.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'124.6万'},
                {id:2,value:'【记录】中国纪录片原声带',imgSrc:'http://p1.music.126.net/rxTBkY67pTp5oOOOLJDMfA==/18516875325233910.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'88.3万'},
                {id:3,value:'摇滚，越南战争与嬉皮士',imgSrc:'http://p1.music.126.net/DbZ8ZfwR2xREBv7zfSGzdQ==/109951163382604539.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'58.8万'},
                {id:4,value:'『港乐』香港音乐大师第三辑：黄霑作品集',imgSrc:'http://p1.music.126.net/--g2cC8VzJGrn940Bix4mQ==/18729081069408776.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'41.7万'},
                {id:5,value:'「高质量英文歌」让你单曲循环的英文歌',imgSrc:'http://p1.music.126.net/Op-a3I7Iy-amnSlzhVcWxw==/18814842976746273.webp?imageView&thumbnail=246x0&quality=75&tostatic=0&type=webp',viewCount:'304.6万'},
            ],
            
        }
    },
    methods:{
        handleClick(tab, event) {
            console.log(tab, event);
          }
        }

})